name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

#     - name: Prepare
#       run: sudo apt update && sudo apt install build-essential

    - name: Build
      run: make WHAT=cmd/kubectl
#       run: make all
#       run: go build -v ./...

    - name: Test
      run: cmd/kubectl version
#       run: go test -v ./...
